name: Deploy to Posit Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Posit Cloud
      run: |
        RSCONNECT_API_KEY=${{ secrets.POSIT_API_KEY }}
        RSCONNECT_SERVER=https://connect.posit.cloud
        RSCONNECT_ACCOUNT=phddmmpy
        rsconnect deploy shiny-python/app.py